<a href="https://colab.research.google.com/github/satishkumar32/assignment/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [12]:
# Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

import numpy as np
arr = np.arange(0, 6)
print(arr.dtype)

int64


In [ ]:
#Given a NumPy array 'arr', check if its data type is float64.

arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype == np.float64)

True


In [ ]:
# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

arr = np.array([1.5, 5+6j, 2])
print(arr.dtype)

complex128


In [ ]:
#Convert an existing NumPy array 'arr' of integers to float32 data type.

arr = np.array([1.5, 2.6, 3.7])
arr = arr.astype(np.float32)
print(arr.dtype)

float32


In [ ]:
#Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

arr = np.array([1.5, 2.6, 3.7])
print(arr.dtype)
arr = arr.astype(np.float32)
print(arr.dtype)

float64
float32


In [ ]:
#Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data type

def array_attributes(arr):
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    result = f"shape {shape}, size {size}, dtype {dtype}"
    return result

s = np.array([1,2,3,4,5])
array_attributes(s)

'shape (5,), size 5, dtype int64'

In [ ]:
#Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

def array_dimension(arr):
  dims = arr.ndim
  result = f"{dims} dimensionality"
  return result

s = np.array([1,2,3,4,5])
array_dimension(s)

'1 dimensionality'

In [ ]:
# Design a function item_size_info that takes a NumPy array as input and returns the item size and the total size in bytes

def item_size_info(arr):
  item_size = arr.itemsize
  total_size = arr.nbytes
  result = f"item size {item_size}, total size {total_size}"
  return result

s = np.array([1,2,3,4,5])
item_size_info(s)

'item size 8, total size 40'

In [ ]:
#Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

def array_strides(arr):
  stride = arr.strides
  result = f"strides {stride}"
  return result

s = np.array([1,2,3,4,5])
array_strides(s)

'strides (8,)'

In [ ]:
#Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape and strides of the array.

def shape_stride_relationship(arr):
  shape = arr.shape
  strides = arr.strides
  result = f"shape {shape}, strides {strides}"
  return result

s = np.array([1,2,3,4,5])
shape_stride_relationship(s)

'shape (5,), strides (8,)'

In [ ]:
#Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of zeros with `n` elements.

def create_zeros_array(arr):
    return np.zeros(n)

n = 5
create_zeros_array(n)


array([0., 0., 0., 0., 0.])

In [ ]:
#Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D NumPy array filled with ones of size `rows x cols`.

def create_ones_matrix(arr1,arr2):
    return np.ones((arr1,arr2))

s1 = 3
s2 = 5
create_ones_matrix(s1,s2)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
#Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified `step`.

def generate_range_array(srt, sop, stp):
      ds = np.arange(srt, sop +1, stp)
      return ds

s1 = 2
s2 = 10
s3 = 2
generate_range_array(s1,s2,s3)

array([ 2,  4,  6,  8, 10])

In [ ]:
#Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as arguments and generates a NumPy array with num equally spaced values between `start` and `stop`

def generate_linear_space(start, stop, num):
    ds = np.linspace(start, stop, num)
    return ds

s1 = 2
s2 = 5
s3 = 10
generate_linear_space(s1,s2,s3)

array([2.        , 2.33333333, 2.66666667, 3.        , 3.33333333,
       3.66666667, 4.        , 4.33333333, 4.66666667, 5.        ])

In [ ]:
#. Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square identity matrix of size `n x n` using `numpy.eye`.

def create_identity_matrix(n):
    ds= np.eye(n)
    return ds

n = 5
create_identity_matrix(n)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
#Write a function that takes a Python list and converts it into a NumPy array.

def convs(ls):
  ds = np.array(ls)
  return ds

ls = [1,2,3,4,5,6]
convs(ls)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the same data.

s = np.array([1,2,3,4,5])
s1 = s.view()
s1

array([1, 2, 3, 4, 5])

In [ ]:
#Write a function that takes two NumPy arrays and concatenates them along a specified axis.

def concatenate_arrays(arr1, arr2, axis):
    ds = np.concatenate((arr1, arr2), axis)
    return ds


s1 = np.array([1,2,3,4,5])
s2 = np.array([1,9,8,7,6])
x_axs = 0
concatenate_arrays(s1, s2, x_axs)

array([1, 2, 3, 4, 5, 1, 9, 8, 7, 6])

In [ ]:
#Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy. concatenate`.

def  concatenate_array(s1, s2, x_axs):
    ds = np.concatenate((s1, s2), x_axs)
    return ds

s1 = np.array([1,2,3,4,5])
s2 = np.array([1.5,9.6,8.4,7.6,6.0])
x_axs = 0
concatenate_array(s1, s2, x_axs)

array([1. , 2. , 3. , 4. , 5. , 1.5, 9.6, 8.4, 7.6, 6. ])

In [ ]:
# Write a function that vertically stacks multiple NumPy arrays given as a list.

def vertically(arr):
  ds = np.vstack(arr)
  return ds

s = np.array([1,2,3,4,5])
vertically(s)

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
#Write a Python function using NumPy to create an array of integers within a specified range (inclusive) with a given step size.

def create_array(start, stop, step):
    ds = np.arange(start, stop + 1, step)
    return ds

s1 = 2
s2 = 10
s3 = 2
create_array(s1,s2,s3)

array([ 2,  4,  6,  8, 10])

In [ ]:
#Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

def create_array(start, stop, step):
    ds = np.linspace(start, stop, 10)
    return ds

s1 = 1
s2 = 5
s3 = 10
create_array(s1,s2,s3)

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [ ]:
#Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

def create_array():
  ds = np.logspace(1, 1000, 5)
  return ds

create_array()

array([1.00000000e+001, 5.62341325e+250,             inf,             inf,
                   inf])

In [ ]:
#Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values are random integers between 1 and 100.

def func(r,c):
  ds = np.random.randint(1, 100, size=(r,c))
  return ds

func(5,3)

array([[33,  5, 96],
       [21, 82, 72],
       [12, 68, 77],
       [72, 40, 85],
       [36, 86,  5]])

In [ ]:
#Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column with zeros. Use NumPy operations within the Pandas DataFrame.

import pandas as pd

data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-10, 20, -30, 40, -50]
}

df = pd.DataFrame(data)
def replace_neg_from_pandas(df):
      df = np.where(df[['A','B']] < 0, 0, df[['A','B']])
      return df

replace_neg_from_pandas(df)


array([[ 1,  0],
       [ 0, 20],
       [ 3,  0],
       [ 0, 40],
       [ 5,  0]])

In [ ]:
# Access the 3rd element from the given NumPy array. arr = np.array([10, 20, 30, 40, 50])

arr = np.array([10, 20, 30, 40, 50])

arr[2]

30

In [ ]:
#Retrieve the element at index (1, 2) from the 2D NumPy array. arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_2d[1,2]

6

In [ ]:
#Using boolean indexing, extract elements greater than 5 from the given NumPy array. arr = np.array([3, 8, 2, 10, 5, 7])

arr = np.array([3, 8, 2, 10, 5, 7])
ds = arr[arr > 5]
ds

array([ 8, 10,  7])

In [ ]:
# Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array. arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[2:5+1]

array([3, 4, 5, 6])

In [ ]:
#Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array. arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

arr_2d[0:2, 1:2+1]

array([[2, 3],
       [5, 6]])

In [ ]:
#Write a NumPy function to extract elements in from a given 2D array based on indices provided in another array.
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
indices = np.array([1])

def extract_elements(arr_2d, indices):
      return arr_2d[indices]

extract_elements(arr_2d, indices)

array([[4, 5, 6]])

In [ ]:
#Create a NumPy function that extracts elements from a 2D array using row and column indices provided in separate arrays.

def extract_elements(arr_2d, row_indices, col_indices):
    return arr_2d[row_indices, col_indices]

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])

extract_elements(arr_2d, row_indices, col_indices)

array([2, 6, 7])

In [ ]:
#Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three separate arrays for each dimension.

def extract_elements(arr_3d, indices_x, indices_y, indices_z):
    return arr_3d[indices_x, indices_y, indices_z]

arr_3d = np.array([[[1, 2, 3], [4, 5, 6], [7, 8, 9]],
                   [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
                   [[19, 20, 21], [22, 23, 24], [25, 26, 27]]])

indices_x = np.array([0, 1, 2])
indices_y = np.array([1, 2, 0])
indices_z = np.array([2, 1, 0])

extract_elements(arr_3d, indices_x, indices_y, indices_z)

array([ 6, 17, 19])

In [ ]:
# Create a NumPy function that filters elements greater than a threshold from a given 1D array using boolean indexing.

def check_threshold(arr, threshold):
    ds = arr[arr > threshold]
    return ds

array1 = np.array([12, 24, 16, 21, 32, 29, 7, 15])
threshold = 20
check_threshold(array1, threshold)

array([24, 21, 32, 29])

In [ ]:
#Write a NumPy function that returns elements from an array where both two conditions are satisfied using boolean indexing.
array1 = np.array([12, 24, 16, 21, 32, 29, 7, 15])
condition1 = 20

def check_threshold(arr, threshold):
    ds = arr[arr > threshold]
    ds2 = ds%2 == 0
    return ds[ds2]

check_threshold(array1, threshold)

array([24, 32])

In [ ]:
# Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

arr_3d = np.array([[1, 2, 3],
                   [10, 11, 12],
                   [19, 20, 21]])

arr_3d + 5

array([[ 6,  7,  8],
       [15, 16, 17],
       [24, 25, 26]])

In [ ]:
# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the corresponding element in arr1 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 1, 2, 3]])

arr1 = arr1.T
arr2 * arr1

[[ 1  2  3  4]
 [10 12 14 16]
 [27  3  6  9]]


In [ ]:
#Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using NumPy broadcasting.

arr1 = np.array([[1, 2, 3, 4]])
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6],
                 [7, 8, 9],
                 [10, 11, 12]])

arr1 = arr1.T
arr2 + arr1

array([[ 2,  3,  4],
       [ 6,  7,  8],
       [10, 11, 12],
       [14, 15, 16]])

In [ ]:
#Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy broadcasting.

arr2 = np.array([[1, 2, 3]])
arr1 = arr2.T
arr2 + arr1

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [ ]:
#Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy broadcasting. Handle the shape incompatibility.

arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])
arr2 = np.array([[1, 2],
                 [3, 4],
                 [5, 6]])
arr2 = arr2.T
arr1 * arr2

array([[ 1,  6, 15],
       [ 8, 20, 36]])

In [ ]:
# Calculate column-wise mean for the given array:

arr = np.array([[1, 2, 3], [4, 5, 6]])

def mean_cal(arr):
  ds = np.mean(arr, axis=0)
  return ds

mean_cal(arr)

array([2.5, 3.5, 4.5])

In [ ]:
#Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

def max_val(arr):
  ds = np.max(arr, axis=1)
  return ds

arr = np.array([[1, 2, 3], [4, 5, 6]])
max_val(arr)

array([3, 6])

In [ ]:
# For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

def index_of_max(arr):
    ds = np.argmax(arr, axis=0)
    return ds

index_of_max(arr)

array([1, 1, 1])

In [ ]:
#For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

def cal_sum(arr):
  ds = np.cumsum(arr, axis=1)
  return ds

cal_sum(arr)

array([[ 1,  3,  6],
       [ 4,  9, 15]])

In [ ]:
#In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

def check_evnn(arr):
  ds = arr % 2 == 0
  return arr[ds]

check_evnn(arr)

array([2, 4, 6])

In [ ]:
#Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

arr = np.matrix(original_array)
m = 2
n = 3
arr.reshape(m,n)

matrix([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

def flatten_arr(arr):
    ds = arr.flatten()
    return ds

flatten_arr(input_matrix)

array([1, 2, 3, 4, 5, 6])

In [ ]:
#Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

ds = np.concatenate((array1, array2), axis=1)
ds

array([[1, 2, 5, 6],
       [3, 4, 7, 8]])

In [ ]:
#Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

np.array_split(original_array, 3)


[array([[1, 2, 3]]), array([[4, 5, 6]]), array([[7, 8, 9]])]

In [ ]:
# Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

original_array = np.insert(arr=original_array, obj=indices_to_insert, values=values_to_insert)
np.delete(arr=original_array, obj=indices_to_delete)

array([ 1, 10,  4, 11,  5])

In [ ]:
#Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10. Perform element-wise addition between `arr1` and `arr2`.

arr1 = np.random.randint(0,10, 5)
arr2 = np.random.randint(0,10, 5)
arr1 + arr2

array([15, 12, 12,  7, 11])

In [ ]:
#Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers from 1 to 10. Subtract `arr2` from `arr1` element-wise.
arr1 = np.arange(10,1, -1)
arr2 = np.arange(1,10)
arr2-arr1

array([-9, -7, -5, -3, -1,  1,  3,  5,  7])

In [ ]:
#Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5. Perform element-wise multiplication between `arr1` and `arr2`.
arr1 = np.random.randint(0,5, 3)
arr2 = np.random.randint(0,5, 3)
print(arr1, arr2)
np.multiply(arr1 , arr2)

[2 2 4] [2 4 2]


array([4, 8, 8])

In [ ]:
# Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1 to 5. Perform element-wise division of `arr1` by `arr2`.
arr1 = np.arange(2,10, 2)
arr2 = np.arange(1,5)
print(arr1, arr2)
np.divide(arr1, arr2)

[2 4 6 8] [1 2 3 4]


array([2., 2., 2., 2.])

In [ ]:
# Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.
arr1 = np.arange(1,5)
arr2 = arr1[::-1]
print(arr1, arr2)
arr1 ** arr2


[1 2 3 4] [4 3 2 1]


array([1, 8, 9, 4])

In [ ]:
#Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])
np.char.count(arr, 'hello').sum()


3

In [ ]:
# Write a function that extracts uppercase characters from a NumPy array of strings.
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
np.char.lower(arr)

array(['hello', 'world', 'openai', 'gpt'], dtype='<U6')

In [ ]:
#Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

arr1 = np.char.replace(arr, 'grape', 'kiwi')
arr1

array(['apple', 'banana', 'kiwi', 'pineapple'], dtype='<U9')

In [ ]:
#Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

np.char.add(arr1, arr2)

array(['HelloOpen', 'WorldAI'], dtype='<U9')

In [ ]:
# Write a function that finds the length of the longest string in a NumPy array.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])
np.char.str_len(arr).max()

9

In [20]:
#Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and standard deviation of the dataset using NumPy's functions.

data = np.random.randint(1, 1001, 100)

mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

print("Mean:", mean)
print("Median:", median)
print("Variance:", variance)
print("Standard Deviation:", std_deviation)

Mean: 498.82
Median: 462.0
Variance: 87118.64759999998
Standard Deviation: 295.1586820677989


In [27]:
#Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the dataset.

data = np.random.randint(1, 101, 50)
ds = np.percentile(data, [25,75])
f"25th percentiles is {ds[0]} and 75th percentiles is {ds[1]}"

'25th percentiles is 27.0 and 75th percentiles is 83.0'

In [33]:
# Create two arrays representing two sets of variables. Compute the correlation coefficient between these arrays using NumPy's `corrcoef` function.

data = np.random.randint(1, 101, 50)
data1 = np.random.randint(1, 101, 50)

np.corrcoef(data, data1)

array([[ 1.        , -0.17621336],
       [-0.17621336,  1.        ]])

In [48]:
#Create two matrices and perform matrix multiplication using NumPy's `dot` function.

data = np.random.randint(1,20, 9)
data1 = np.random.randint(1,20, 9)

data = np.reshape(data, (3,3))
data1 = np.reshape(data1, (3,3))

np.dot(data, data1)

array([[318, 181, 265],
       [471, 247, 244],
       [514, 295, 279]])

In [51]:
# Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th percentiles along with the first and third quartiles.

data = np.random.randint(1, 1001, 50)

percentiles = np.percentile(data, [10, 25, 50, 75, 90])

print("10th percentile:", percentiles[0])
print("25th percentile (Q1):", percentiles[1])
print("50th percentile (median):", percentiles[2])
print("75th percentile (Q3):", percentiles[3])
print("90th percentile:", percentiles[4])

10th percentile: 229.00000000000003
25th percentile (Q1): 330.75
50th percentile (median): 559.0
75th percentile (Q3): 773.0
90th percentile: 879.0


In [59]:
#Create a NumPy array of integers and find the index of a specific element.

data = np.arange(1,10+1)

ds = np.where(data == 5)
ds

(array([4]),)

In [61]:
#Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

ds = arr > 20
arr[ds]

array([25, 42, 30])

In [62]:
# Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])

ds = arr % 3 == 0

arr[ds]

array([12, 15])

In [84]:
# Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

ds = (arr >= 20) & (arr <= 40)
arr[ds]

array([20, 30, 40])

In [88]:
# For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

arr.dtype.byteorder

'='

In [89]:
#For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

arr.byteswap()

array([16777216, 33554432, 50331648], dtype=int32)

In [90]:
#For the given NumPy array, swap its byte order without modifying the original array using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

arr.newbyteorder()

array([16777216, 33554432, 50331648], dtype='>i4')

In [93]:
#For the given NumPy array and swap its byte order conditionally based on system endianness using `newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

if arr.dtype.byteorder == '=':
    system_endianness = np.dtype(int).byteorder
else:
    system_endianness = arr.dtype.byteorder

if system_endianness == '<':
    swapped_arr = arr.newbyteorder('>')
elif system_endianness == '>':
    swapped_arr = arr.newbyteorder('<')
else:
    swapped_arr = arr

print("Original array:", arr)
print("Original array byte order:", arr.dtype.byteorder)
print("Swapped array:", swapped_arr)
print("Swapped array byte order:", swapped_arr.dtype.byteorder)

Original array: [1 2 3]
Original array byte order: =
Swapped array: [1 2 3]
Swapped array byte order: =


In [123]:
# Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.
arr = np.arange(1, 10+1)
arr_copy = arr.copy()
arr_copy[2] = 100
print(arr, arr_copy)

[ 1  2  3  4  5  6  7  8  9 10] [  1   2 100   4   5   6   7   8   9  10]


In [124]:
#Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

arr = np.matrix(np.reshape(np.arange(1, 10), (3,3)))
view_slice = arr[2:]
view_slice[0,1] = 11
print(arr, view_slice)

[[ 1  2  3]
 [ 4  5  6]
 [ 7 11  9]] [[ 7 11  9]]


In [137]:
# Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.
array_a = np.arange(1, 13).reshape(4, 3)
view_b = array_a[2:]
view_b = view_b + 5
print(array_a)
print(view_b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[[12 13 14]
 [15 16 17]]


In [143]:
# Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it reflects changes in the original `orig_array`.
orig_array = np.arange(1, 9).reshape(2, 4)
reshaped_view = orig_array.reshape(4, 2)
reshaped_view[2,1] = 10
print(orig_array, reshaped_view)

[[ 1  2  3  4]
 [ 5 10  7  8]] [[ 1  2]
 [ 3  4]
 [ 5 10]
 [ 7  8]]


In [147]:
#Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

data = np.arange(1, 13).reshape(3, 4)
data_copy = data.copy()
data_copy[data_copy > 5] = 10
print(data, data_copy)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] [[ 1  2  3  4]
 [ 5 10 10 10]
 [10 10 10 10]]


In [157]:
#Create two matrices A and B of identical shape containing integers and perform addition and subtraction operations between them.

arr = np.matrix(np.reshape(np.arange(1, 10), (3,3)))
arr1 = np.matrix(np.reshape(np.arange(31, 40), (3,3)))
print(arr + arr1)
print(arr1 - arr)

[[32 34 36]
 [38 40 42]
 [44 46 48]]
[[30 30 30]
 [30 30 30]
 [30 30 30]]


In [167]:
#Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.
c = np.matrix(np.reshape(np.arange(1, 7), (3,2)))
d = np.matrix(np.reshape(np.arange(31, 39), (2,4)))
c * d

matrix([[101, 104, 107, 110],
        [233, 240, 247, 254],
        [365, 376, 387, 398]])

In [168]:
#Create a matrix `E` and find its transpose.

c = np.matrix(np.reshape(np.arange(1, 7), (3,2)))
c.T

matrix([[1, 3, 5],
        [2, 4, 6]])

In [175]:
#Generate a square matrix `F` and compute its determinant.
F = np.random.randint(1, 10, (3, 3))
np.linalg.det(F)

-26.000000000000004

In [176]:
#Create a square matrix `G` and find its inverse.

G = np.random.randint(1, 10, (3, 3))
np.linalg.inv(G)

array([[ 0.30434783,  0.47826087, -0.91304348],
       [-0.34782609, -1.26086957,  2.04347826],
       [ 0.17391304,  1.13043478, -1.52173913]])